FROM python:3.10.5-slim

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH $PYTHONPATH:/code/src

ENV APP_HOME /code
WORKDIR /$APP_HOME

COPY . $APP_HOME/

COPY requirements-bot.txt requirements.txt
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "-m", "bot"]
