# syntax=docker/dockerfile:1

FROM python:3.10.5-slim

ARG BASE_VERSION="v1.0.0"
ARG GIT_COMMIT="unknown"

ENV BASE_VERSION=$BASE_VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=$PYTHONPATH:/code/src

ENV APP_HOME=/code
WORKDIR /$APP_HOME

COPY requirements-bot.txt requirements.txt
RUN pip install -r requirements.txt

COPY . $APP_HOME/

LABEL org.opencontainers.image.title="Bot"
LABEL org.opencontainers.image.version=$BASE_VERSION
LABEL org.opencontainers.image.revision=$GIT_COMMIT
LABEL org.opencontainers.image.created="${BUILD_DATE}"

ENTRYPOINT ["python", "-m", "bot"]
