[tox]
isolated_build = True
envlist = py311

[testenv]
deps =
       pytest
       pytest-asyncio
       pytest-mock
       -rrequirements-bot.txt
       -rrequirements-fetcher.txt
commands = pytest -vvv src/tests/
