{{- if and .Values.postgresql.enabled (not .Values.postgresql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mvcr-application-checker.fullname" . }}-postgresql
  labels:
    {{- include "mvcr-application-checker.componentLabels" (dict "context" . "component" "postgresql") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
