{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mvcr-application-checker.fullname" . }}-postgresql
  labels:
    {{- include "mvcr-application-checker.componentLabels" (dict "context" . "component" "postgresql") | nindent 4 }}
spec:
  serviceName: {{ include "mvcr-application-checker.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "mvcr-application-checker.selectorLabels" (dict "context" . "component" "postgresql") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mvcr-application-checker.componentLabels" (dict "context" . "component" "postgresql") | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mvcr-application-checker.secretName" . }}
                  key: DB_PASSWORD
          {{- with .Values.postgresql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "mvcr-application-checker.fullname" . }}-postgresql-init
        {{- if .Values.postgresql.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.persistence.existingClaim }}
        {{- else }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mvcr-application-checker.fullname" . }}-postgresql
        {{- end }}
{{- end }}
