apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mvcr-application-checker.secretName" . }}
  labels:
    {{- include "mvcr-application-checker.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  RABBIT_PASSWORD: {{ .Values.secrets.rabbitPassword | quote }}
---
{{- if and (not .Values.secrets.rabbitSSL.existingSecret) (or (and .Values.rabbitmq.enabled .Values.rabbitmq.ssl.enabled) (and (not .Values.rabbitmq.enabled) .Values.externalRabbitmq.ssl.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mvcr-application-checker.rabbit.sslSecretName" . }}
  labels:
    {{- include "mvcr-application-checker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.rabbitSSL.caCrt }}
  ca.crt: {{ .Values.secrets.rabbitSSL.caCrt | b64enc }}
  {{- end }}
  {{- if .Values.secrets.rabbitSSL.serverCrt }}
  server.crt: {{ .Values.secrets.rabbitSSL.serverCrt | b64enc }}
  {{- end }}
  {{- if .Values.secrets.rabbitSSL.serverKey }}
  server.key: {{ .Values.secrets.rabbitSSL.serverKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.rabbitSSL.clientCrt }}
  client.crt: {{ .Values.secrets.rabbitSSL.clientCrt | b64enc }}
  {{- end }}
  {{- if .Values.secrets.rabbitSSL.clientKey }}
  client.key: {{ .Values.secrets.rabbitSSL.clientKey | b64enc }}
  {{- end }}
{{- end }}
