{{- if .Values.fetcher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mvcr-application-checker.fullname" . }}-fetcher
  labels:
    {{- include "mvcr-application-checker.componentLabels" (dict "context" . "component" "fetcher") | nindent 4 }}
spec:
  replicas: {{ .Values.fetcher.replicas }}
  selector:
    matchLabels:
      {{- include "mvcr-application-checker.selectorLabels" (dict "context" . "component" "fetcher") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mvcr-application-checker.componentLabels" (dict "context" . "component" "fetcher") | nindent 8 }}
    spec:
      containers:
        - name: fetcher
          image: "{{ .Values.fetcher.image.repository }}:{{ .Values.fetcher.image.tag }}"
          imagePullPolicy: {{ .Values.fetcher.image.pullPolicy | default "IfNotPresent" }}
          {{- if and .Values.metrics.enabled .Values.metrics.fetcher.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.fetcher.privileged }}
          securityContext:
            privileged: true
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mvcr-application-checker.fullname" . }}-fetcher
          env:
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mvcr-application-checker.secretName" . }}
                  key: RABBIT_PASSWORD
          volumeMounts:
            - name: fetcher-data
              mountPath: /code/output
            {{- if .Values.fetcher.ssl.enabled }}
            - name: ssl-certs
              mountPath: /etc/ssl/
              readOnly: true
            {{- end }}
          {{- with .Values.fetcher.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: fetcher-data
          emptyDir: {}
        {{- if .Values.fetcher.ssl.enabled }}
        - name: ssl-certs
          secret:
            secretName: {{ .Values.fetcher.ssl.existingSecret | default (include "mvcr-application-checker.rabbit.sslSecretName" .) }}
        {{- end }}
{{- end }}
