{{- if .Values.rabbitmq.enabled }}
{{- if or .Values.rabbitmq.ssl.enabled .Values.rabbitmq.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mvcr-application-checker.fullname" . }}-rabbitmq
  labels:
    {{- include "mvcr-application-checker.componentLabels" (dict "context" . "component" "rabbitmq") | nindent 4 }}
data:
  {{- if .Values.rabbitmq.ssl.enabled }}
  rabbitmq.conf: |
    listeners.ssl.default = 5671
    ssl_options.verify = verify_peer
    ssl_options.fail_if_no_peer_cert = true
    ssl_options.cacertfile = /etc/ssl/ca.crt
    ssl_options.certfile = /etc/ssl/server.crt
    ssl_options.keyfile = /etc/ssl/server.key
  {{- end }}
  {{- if .Values.rabbitmq.metrics.enabled }}
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus].
  metrics.conf: |
    management_agent.disable_metrics_collector = true
  {{- end }}
{{- end }}
{{- end }}
