name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "deploy/mvcr-application-checker-helm/**"
  pull_request:
    paths:
      - "deploy/mvcr-application-checker-helm/**"

jobs:
  helm:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Read chart version
        run: |
          VERSION=$(grep '^version:' deploy/mvcr-application-checker-helm/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Chart version: $VERSION"

      - name: Lint chart
        run: helm lint deploy/mvcr-application-checker-helm/

      - name: Package chart
        run: helm package deploy/mvcr-application-checker-helm/ --destination .

      - name: Login to DockerHub OCI
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push chart to OCI registry
        if: github.event_name == 'push'
        run: helm push mvcr-application-checker-helm-${{ env.VERSION }}.tgz oci://docker.io/olegeech
